-- Baseline for the schema that existed before Flyway was introduced.
-- Existing non-empty databases are recorded at version 1; new databases run this script.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$;

CREATE TABLE public.ingestion_runs (
    id uuid NOT NULL,
    started_at timestamp without time zone NOT NULL,
    finished_at timestamp without time zone,
    status character varying(20) NOT NULL,
    error text,
    products_processed integer DEFAULT 0,
    CONSTRAINT ingestion_runs_pkey PRIMARY KEY (id)
);

CREATE TABLE public.platforms (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    url text NOT NULL
);

CREATE TABLE public.products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform integer NOT NULL REFERENCES public.platforms(id) ON DELETE CASCADE,
    external_id text NOT NULL,
    name text,
    url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT products_platform_external_id_key UNIQUE (platform, external_id)
);

CREATE TABLE public.price_history (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    price numeric(10,2) NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT unique_price_snapshot UNIQUE (product_id, recorded_at)
);

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    username character varying(100) NOT NULL UNIQUE,
    email character varying(255) UNIQUE,
    hashed_password text NOT NULL,
    role character varying(20) DEFAULT 'USER'::character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    is_superuser boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.refresh_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_revoked boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracking_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracked_product_id integer,
    tracked_product_price numeric(19,4),
    platform_id integer,
    status character varying(30),
    tracked_at date DEFAULT now()
);

CREATE TABLE public.tracking_urls (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_request_id integer,
    url character varying(255),
    status character varying(30)
);

CREATE INDEX idx_ingestion_runs_started_at ON public.ingestion_runs (started_at DESC);
CREATE INDEX idx_ingestion_runs_status ON public.ingestion_runs (status);
CREATE INDEX idx_price_history_product_time ON public.price_history (product_id, recorded_at);
CREATE INDEX idx_refresh_expires_at ON public.refresh_tokens (expires_at);
CREATE INDEX idx_refresh_token_hash ON public.refresh_tokens (token_hash);
CREATE INDEX idx_refresh_user_id ON public.refresh_tokens (user_id);
CREATE INDEX idx_users_email ON public.users (email);
CREATE INDEX idx_users_username ON public.users (username);

CREATE TRIGGER trg_update_users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
